### ISSUE TITLE
Sticky scrollspy styling not covering full width; creates horizontal scroll

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#72]
![image](https://user-images.githubusercontent.com/5004319/29031054-fbee0010-7b5a-11e7-98d9-c107f5595fe3.png)

**Comment by andycochran** [comment]
I think this is actually caused by the absolute-positioned "hidden" tooltips.

**Comment by andycochran** [comment]
Yup. We're facing this issue: 
https://github.com/sir-dunxalot/ember-tooltips/issues/111

**Comment by andycochran** [comment]
@allthesignals,  I don't like it but this fixes it: 

```scss
html {
  overflow: hidden;
}

html, body {
  width: 100%;
  height: 100%;
  overflow-x: hidden;

  @include breakpoint(large) {
    height: 100%;
    overflow: hidden;
  }
}
```
