### ISSUE TITLE
Prototype a print-friendly view for each CD profile

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#79]

**Comment by chriswhong** [comment]
This issue is done when:

- [ ] Add Print call to action to profile pages
- [ ] Layout is optimized for print

**Comment by allthesignals** [comment]
@andycochran current printout view:
[LabsCommunityPortal.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46c4959830a18ca482fcb14ab044c09b3b52267f6b48e13b628ae92dbc56395b4d5a47ab175e0a42f4fc8b28a1b46d708a5903ead7680d73902f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e7898e4c3f1600108df65827ed.pdf)

**Comment by andycochran** [comment]
We should start by changing the `$print-breakpoint` to `medium` in `_setting.scss`, which will keep the map and content in the same full-width column. From there, we can use Foundation's built-in [Print Styles](http://foundation.zurb.com/sites/docs/typography-base.html#print-styles) and its `.hide-for-print` class to clean up the layout. 

There's also a `$print-hrefs` settings var that determines if we want URLs to print with… 
```scss
a[href]:after { content: ' (' attr(href) ')'; }
```
^ I'm not sure how helpful this is for this particular app. 

We may also want to disable the `$print-transparent-backgrounds` setting (which is meant to save ink), as it's making the map UI transparent. Tho, we don't really need map UI in print.  We could… 

```scss
// keep a list of stuff we wanna hide for print
@media print {
  .ui-element-1,
  .ui-element-2,
  .ui-element-3 {
    display: none !important; 
  }
}
```
